[package]
name = "scemu"
version = "0.7.10"
authors = ["sha0coder"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
<<<<<<< HEAD
libscemu = "0.17.1"
#libscemu = { path = "/home/sha0/src/libscemu/" }
=======
#libscemu = "0.16.7"
libscemu = { path = "/home/sha0/src/libscemu/" }
>>>>>>> ed36c34113e24b9a1e43d89b5f6170a7cf94daec
#libscemu = { path = "/Users/sha0coder/src/libscemu/" }
