[workspace]
resolver = "2"
members = [
    "pymwemu",
    "libmwemu",
    "mwemu"
]

[profile.release]
debug = 0
strip = true
opt-level = 3
panic = 'unwind'

[profile.dev]
debug = "full"
opt-level = 1
panic = 'unwind'
