# Only format imports, leave everything else alone
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Disable all other formatting
format_code_in_doc_comments = false
format_strings = false
format_macro_matchers = false
normalize_comments = false
normalize_doc_attributes = false
wrap_comments = false
