[package]
name = "pymwemu"
version = "0.9.12"
edition = "2021"
description = "x86 32/64bits and system internals emulator, for securely emulating malware and other stuff."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pymwemu"
crate-type = ["cdylib", "rlib"]

[features]
default = ["pyo3/extension-module"]
test-with-python = ["pyo3/auto-initialize"]

[dependencies.pyo3]
version = "0.26"
features = ["extension-module"]  # default

[dev-dependencies]
pyo3 = { version = "0.26", features = ["auto-initialize"] }

[dependencies]
env_logger = "0.11.6"
libmwemu = { path = "../libmwemu" }
log = "0.4.22"
iced-x86 = "1.21.0"


