name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      # TODO: fail pipeline if formatting fails
      - name: Check formatting
        run: cargo fmt --all -- --check || true
      
      # TODO: fail pipeline if clippy fails
      - name: Run clippy
        run: cargo clippy -- -D warnings || true
      
      - name: Build
        run: cargo build --release --verbose
      
      - name: Run libmwemu tests (linux / mac)
        if: runner.os != 'Windows'
        run: make tests 

      - name: Run libmwemu tests (windows 
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
           Invoke-WebRequest -Uri "https://github.com/sha0coder/mwemu/releases/download/maps/test.zip"  -OutFile "test.zip"
           Expand-Archive -Path "test.zip" -Destination "test"
           cargo test --release --package libmwemu --verbose

      - name: Run pymwemu tests
        if: runner.os != 'Windows'
        run: make pytests

      - name: Install cargo-tarpaulin
        if: runner.os == 'Linux'
        run: cargo install cargo-tarpaulin

      - name: Run coverage
        if: runner.os == 'Linux'
        run: cargo tarpaulin --out Xml --timeout 200

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sha0coder/mwemu
