name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      # TODO: fail pipeline if formatting fails
      - name: Check formatting
        run: cargo fmt --all -- --check || true
      
      # TODO: fail pipeline if clippy fails
      - name: Run clippy
        run: cargo clippy -- -D warnings || true
      
      - name: Build
        run: cargo build --release --verbose
      
      - name: Run libmwemu tests
        run: make tests 

      - name: Run pymwemu tests
        run: make pytests

      - name: Run Python Tests
        run: make pytests2

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run coverage
        run: cargo tarpaulin --out Xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sha0coder/mwemu
